### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KellyGabony** [Vinyzu/Botright#10]
![image](https://user-images.githubusercontent.com/108149541/205934678-139d2eac-7029-45d5-ac66-33403c68a58b.png)

**Comment by Vinyzu** [comment]
Oups, i forgot it in the required packages. Will be fixed today.

Just do `pip install hcaptcha_challenger` and it will be fixed. (note theres another bug rn do it maight not work anyways)

**Comment by Vinyzu** [comment]
Fixed: https://github.com/Vinyzu/Botright/commit/7d6701f434a450845d3386b0ae90d0943d82c0f5
