### ISSUE TITLE
[Question] Does work with chrome??

### ISSUE THREAD

**Issue by bettonna** [Vinyzu/Botright#107]
**Describe your quesiton**
A clear and concise question.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

Thank you brother, Does it work as a chrome extension?  , I tried to do this but I failed  , Can you do this in future updates? thank you again

**Comment by Vinyzu** [comment]
Botright works with chrome extensions.
But botright isnt and cant be a chrome extension.
