### ISSUE TITLE
[BUG]  RuntimeError: PyTourchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by FuckingToasters** [Vinyzu/Botright#11]
**Describe the bug**
I tried to install Botright on a Linux Ubuntu Server but due to some smaller issues (like installing tensorflow on a server without gpu and cpu only) i needed to manually download Botright and change the tensorflow requirement in setup.py to tensorflow-cpu. After Botright were installed sucessfully on the Linux System i ran my script which then produced the Error mentioned in the Title.

**To Reproduce**
1. Use a ubuntu Linux Machine (I used Linode)
2. Got Clone this repo, cd into the cloned repo
3. Change the requirement list in setup.py to tensorflow-cpu instead of tensorflow
4. Install it using `pip install -e .`

**Expected behavior**
It should download the AI Files, open Browser, solve captcha.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/94435104/206172294-ff3e22df-991e-4ef4-89fd-dbc75ef6c315.png)

**Desktop (Bash only - No Desktop present):**
 - OS: Ubuntu
 - Version: 22.04 LTS

**Comment by Vinyzu** [comment]
You maight wanna look into this issue: https://github.com/pytorch/pytorch/issues/31620

Anyways, it doesnt seem like an issue of botright so as long as you cant insure that it is one of this package i wont look further into it.

**Comment by Vinyzu** [comment]
No further information was given. Not an issue of Botright.
