### ISSUE TITLE
[BUG] cannot import name 'keras' from 'tensorflow' (unknown location) or No module named 'tensorflow.compat'

### ISSUE THREAD

**Issue by Impre-visible** [Vinyzu/Botright#14]
**Describe the bug**
When I import botright, I have the first error : 
```
cannot import name 'keras' from 'tensorflow' (unknown location)
```

so I look at the error, and I see in recaptcha.py in botright that you import keras from tensorflow, so I change it to import only keras cause it can be an alone lib. WhenI do that, I have another error,
```
 No module named 'tensorflow.compat'
```

this error come from the keras engine, so don't think you can do a lot about the second error, but maybe the first

**Code Sample**
```py
import botright
```
**To Reproduce**
1. Import botright

**Expected behavior**
Just import it :'D

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
 - Python version: 3.10.0
 - Botright version: 3.2.2
 - Tensorflow version: 2.11.0

**Comment by luxkatana** [comment]
👋 can you maybe try updating **tensorflow**? That might solve the issue.
```
python -m pip install  tensorflow -U
```

**Comment by Vinyzu** [comment]
No further information was given. Reopen if the Issue persists.
