### ISSUE TITLE
[BUG] Big bug with your new update

### ISSUE THREAD

**Issue by K2pl2r** [Vinyzu/Botright#17]
Hi, "ModuleNotFoundError: No module named 'browsers'" i checked everything, no module of this name is installable and you have not mentioned it anywhere.

**Comment by iceFbr** [comment]
he forgot recaptcha also... kkkk

**Comment by Vinyzu** [comment]
Fixed with update [v0.4](https://github.com/Vinyzu/Botright/commit/d8a00b5b6ed596bf3067437bbf2e01cbfad4c00b)
