### ISSUE TITLE
[BUG] waiting for frame_locator("xpath=//iframe[contains(@title, 'hCaptcha challenge')]").locator("xpath=//div[@class='challenge-view']//canvas")

### ISSUE THREAD

**Issue by lxntagram** [Vinyzu/Botright#20]
```
import asyncio

import botright


async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    page = await browser.new_page()

    # Continue by using the Page
    await page.goto("https://accounts.hcaptcha.com/demo")
    await page.solve_hcaptcha()
    await page.wait_for_timeout(100000 * 10000)
if __name__ == "__main__":
    asyncio.run(main()) 
```

I'm getting
waiting for frame_locator("xpath=//iframe[contains(@title, 'hCaptcha challenge')]").locator("xpath=//div[@class='challenge-view']//canvas")
so often. Is there a way to fix it?

**Comment by Vinyzu** [comment]
Trying to repro…

**Comment by lxntagram** [comment]
How was it?

**Comment by Vinyzu** [comment]
Okay, please reopen this issue at [hCaptcha-Challenger](https://github.com/QIN2DIM/hcaptcha-challenger/issues). Also, please test the test files given in the examples folder to reproduce this error on different (approved) code.
