### ISSUE TITLE
[Question] Initialize BrowserContext

### ISSUE THREAD

**Issue by krsamue101** [Vinyzu/Botright#22]
Does botright have plans to support the context feature like playwright?

**Comment by Vinyzu** [comment]
Why would you believe that botright doesnt already support it? In other words: Botright should already support it…

**Comment by krsamue101** [comment]
Because new_context() didn't worked..?
```
import asyncio
import botright

async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    context = await browser.new_context()
    page = await context.new_page()
    # Continue by using the Page
    await page.goto("https://google.com")
    await botright_client.close()
if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by Vinyzu** [comment]
The Context you mention isnt an [APIRequestContext](https://playwright.dev/python/docs/api/class-apirequestcontext), but an [BrowserContext](https://playwright.dev/python/docs/api/class-browsercontext). Actually, `await botright_client.new_browser()` already returns a [BrowserContext](https://playwright.dev/python/docs/api/class-browsercontext) as described in the [Docs](https://github.com/Vinyzu/Botright/blob/main/docs/botright.rst#newbrowser).
So theres no need for you to create an extra BrowserContext.
