### ISSUE TITLE
[BUG] HCaptcha on discord not loaded

### ISSUE THREAD

**Issue by krsamue101** [Vinyzu/Botright#23]
![image](https://github.com/Vinyzu/Botright/assets/105032235/9346abcd-27e8-4258-b92d-ceccbbd65dcc)
Tried changing ip but not worked. But hcaptcha loads on other browsers( chrome, edge, brave.. etc) loaded captcha successfully
```
async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    page = await browser.new_page()
    await page.goto("https://discord.com") # load|domcontentloaded|networkidle|commit
```

**Comment by Vinyzu** [comment]
Confirmed, sometimes takes 1-2 reloads for it to load. Will investigate

**Comment by TheRealPerson98** [comment]
Also having this problem.

**Comment by lxntagram** [comment]
When it will be fixed? It seems argument issue

**Comment by Vinyzu** [comment]
Will work on it soon

**Comment by lxntagram** [comment]
Now it loads hcaptcha but it refresh captcha itself and closes captcha

https://github.com/Vinyzu/Botright/assets/133577870/54426aaf-da5e-4834-829c-175622907972

**Comment by Vinyzu** [comment]
Its probably because hcaptcha_challenger is not actively maintained anymore so these tasks are unsupported. No issue in botright.
