### ISSUE TITLE
Error installing botright due to scikit_image-0.21.0.tar.gz metadata preparation

### ISSUE THREAD

**Issue by jesuisen50** [Vinyzu/Botright#25]
I am facing an issue while trying to install the botright Python module, which requires the installation of various dependencies. During the installation process, it encounters an error specifically related to the preparation of metadata for scikit_image-0.21.0.tar.gz.

Error Message:
[Error.txt](https://github.com/scikit-image/scikit-image/files/13767017/Error.txt)

Expected Behavior:
I expected the installation of botright to proceed smoothly without encountering errors related to the preparation of metadata for scikit_image-0.21.0.tar.gz.

Environment:
Python Version:  3.12.0
Pip Version: 23.3.2
Additional Information:

I can successfully install the latest version of scikit_image without any issues.
Provide any other relevant information that might help identify and resolve the issue.

Thank you for your assistance in resolving this issue.

**Comment by bradleyb254** [comment]
same issue, what are we doing wrong?

**Comment by Vinyzu** [comment]
If i remember correctly, the scikit image requirement isnt even used, so it can be deleted. Will be fixed in the next update.

**Comment by Vinyzu** [comment]
Fixed in v0.5.
Update via `pip install botright --upgrade`.
