### ISSUE TITLE
How to apply to your BotRight?

### ISSUE THREAD

**Issue by Wtcity22** [Vinyzu/Botright#26]
How should I apply it to playwright or your Botright? Currently, your Botright can pass Akamai, but Kasada cannot. I am thinking how to apply the fingerprints you collected directly to your Botright or Playwright.
In addition, I found DrissionPage, an open source automation library that can 100% pass CloudFlare, but it cannot achieve random fingerprints. [https://g1879.gitee.io/drissionpagedocs/](https://g1879.gitee.io/drissionpagedocs/)

Finally, I want to ask, how can I pass Kasada?For example, this website: 

[https://www.aircanada.com/aeroplan/redeem/availability/outbound?org0=JFK&dest0=LHR&departureDate0=2024-01-01&lang=en-CA&tripType=O&ADT=1&YTH=0&CHD=0&INF=0&INS=0&marketCode= INT ](https://www.aircanada.com/aeroplan/redeem/availability/outbound?org0=JFK&dest0=LHR&departureDate0=2024-01-01&lang=en-CA&tripType=O&ADT=1&YTH=0&CHD=0&INF=0&INS=0&marketCode=INT)

has both Akamai and Kasada encryption. It can currently pass Akamai 100%, but Kasada cannot. With frequent requests, it will block the environment. How to solve it?

**Comment by bluefire1999** [comment]
DrissionPage can also use random browser fingerprints.

**Comment by Vinyzu** [comment]
Chrome-Fingerprints were implemented in v0.5.
Please open a seperate issue for the Kasada Detection.
@Wtcity22
