### ISSUE TITLE
How can I add args?

### ISSUE THREAD

**Issue by Sh4rK157** [Vinyzu/Botright#27]
Newbie question guys, but how can I add args to Botright?

    context_args = {
        'viewport': {'width': 1920, 'height': 1080},
    }

    options = {
        'args': [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            # '--single-process',
            '--disable-gpu'
        ],
        'headless': False
    }

    botright_client = await botright.Botright(**options, cache_responses=True)
    browser = await botright_client.new_browser(**context_args)
    page = await browser.new_page()

I have this slice of code and context args works fine but idk where to place my browser args (in original playwrite it works).

**Comment by Vinyzu** [comment]
In your case you can extend the command line flags by using
`botright_client.flags.extend(options["args"])`

**Comment by Sh4rK157** [comment]
> In your case you can extend the command line flags by using `botright_client.flags.extend(options["args"])`

Thanks, that helped me a lot!
