### ISSUE TITLE
Is it possible to make a browser extension based on this for Chrome?

### ISSUE THREAD

**Issue by Zero3K** [Vinyzu/Botright#28]
*subject*

**Comment by Vinyzu** [comment]
Generally: no.
This package relies on many outside factors as command-line flags, cdp interactions or even engine patches.
You maight be able to Use [chrome-fingerprints](https://github.com/Vinyzu/chrome-fingerprints/) (with many tweaks) in an extension though.
But generally, what ive learned concerning browser stealth is that you should usually try to avoid js-patching, as its incredibly hard to not get detected there. Thats why i think a "stealth" browser extension is a bad idea.
You maight want to look into stealth, or privacy-focused browsers instead if you want a everyday/simple solution.

**Comment by Zero3K** [comment]
I just wanted a way to be able to solve CAPTCHAs automatically.
