### ISSUE TITLE
Error with PIP package 

### ISSUE THREAD

**Issue by GodlyShima** [Vinyzu/Botright#35]
ERROR: Cannot install botright because these package versions have conflicting dependencies.

The conflict is caused by:
    hcaptcha-challenger 0.10.1.post2 depends on onnxruntime==1.16.1
    hcaptcha-challenger 0.10.1.post1 depends on onnxruntime==1.16.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by GodlyShima** [comment]
this command: python -m pip install botright==0.5

**Comment by C0dins** [comment]
what version of python are you using?

**Comment by Vinyzu** [comment]
Cant reproduce. Please providemore information abooutthe python env and os youre using.

**Comment by C0dins** [comment]
Python 3.12.1 windows 11 did not work and then i installed python 3.11.x and it works

**Comment by Vinyzu** [comment]
Great. Python >=3.12 isn't supported by that many packages, so staying on 3.11 is generally not that bad of an idea.
