### ISSUE TITLE
install ungoogled-chromium

### ISSUE THREAD

**Issue by gobblydygook** [Vinyzu/Botright#36]
How or where should I install an ungoogled-chromium binary so that Botright will find it?

**Comment by Vinyzu** [comment]
You can download the binaries @ [ungoogled-software](https://ungoogled-software.github.io/ungoogled-chromium-binaries/)

**Comment by marcusdiy** [comment]
how to use a portable version? This doesn't work
botright_client = await botright.Botright(headless=False, user_action_layer = True)
browser = await botright_client.new_browser(browser_path=UNGOOGLED_PATH)

**Comment by gobblydygook** [comment]
You need to create a /usr/share/applications/chromium.desktop file with the location of the portable executable, eg:
```
[Desktop Entry]
Type=Application
Name=Ungoogled Chromium
Exec=/usr/local/ungoogled-chromium_122.0.6261.69-1_linux/chrome
Comment=Chrome without the spyware
Categories=WebBrowser
```

Then run the script using an X wrapper, eg
`xvfb-run -a python3 script.py`

**Comment by allail-qadrillah** [comment]
how to doing that on windows?
