### ISSUE TITLE
[Question]  How to give user data directory

### ISSUE THREAD

**Issue by jeevithakannan2** [Vinyzu/Botright#50]
I want to add the user data directory to my program. I tried to define user directory like playwright but it didn't work out. Is there any way to give user data directory?

**Comment by Vinyzu** [comment]
There is currently no way of passing your own User Data Directory.
I maight implement it in the next update, which will also change some of the browser initialization, so you can keep an eye on it whether it gets implemented.
Ill keep this Issue open until the next Update releases.

**Comment by vladcooks** [comment]
Has there been an update? I don't see anything in the documentation.

**Comment by jeevithakannan2** [comment]
I don't know, I am not using botright. As I am not using botright I am going to close this issue.
