### ISSUE TITLE
[BUG] Infinite script loop  🤷🏻‍♂️

### ISSUE THREAD

**Issue by tommylge** [Vinyzu/Botright#57]
**Describe the bug**
Infinite loop on script using botright.
The browser (chrome / chromium...) starts by itself, automated by the script i've made (demo example, nothing particular).
But the script keeps running, even if i stop my script. It just keeps launching the browser and process the script.

**Code Sample**
```py
import asyncio

import botright


async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser()
    page = await browser.new_page()

    # Continue by using the Page
    await page.goto("https://google.com")

    await botright_client.close()


if __name__ == "__main__":
    asyncio.run(main())
```

**To Reproduce**
I don't know, just got a venv, and running with `python main.py`

**Expected behavior**
Expect the script to just run once, not forever.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma (Apple M2)
 - Version 14.3.1 (23D60)
 - Python 3.11.5
 - pip 24.0 from venv/lib/python3.11/site-packages/pip (python 3.11)

**Comment by Vinyzu** [comment]
You maight wanna try:
```py
if __name__ == "__main__":
    loop = asyncio.ProactorEventLoop()
    loop.run_until_complete(main())
```

**Comment by tommylge** [comment]
works. thanks a lot!
