### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alenkimov** [Vinyzu/Botright#58]
**Describe the bug**
Google pages don't load with proxies. And if I open a new tab manually from the same browser, the page will load normally. The problem is clearly not in my proxies.

**Code Sample**
```python
import asyncio
import botright


async def main():
    botright_client = await botright.Botright()
    browser = await botright_client.new_browser(
        proxy="user:pass@ip:port",
    )
    page = await browser.new_page()
    await page.goto("https://www.myip.com")  # loads

    page = await browser.new_page()
    await page.goto("https://accounts.google.com")  # fails to load!!!
    await page.wait_for_timeout(5000)
    await botright_client.close()

if __name__ == "__main__":
    asyncio.run(main())
```

**Screenshots**
![image](https://github.com/Vinyzu/Botright/assets/57112140/a837552e-9b7e-4d18-ba68-bafc098fb46d)

**Desktop:**
 - Windows 11

**Comment by alenkimov** [comment]
![pycharm64_kxCHnLNpP5](https://github.com/Vinyzu/Botright/assets/57112140/3c9483ea-38a0-497f-9b38-4f88df316f7e)

**Comment by Vinyzu** [comment]
I dont think this issue has anything to do with the thread(un)safeness.
Also, this behaviour works in Playwright so it is exptected to work in botright.
Im investingating.

**Comment by Vinyzu** [comment]
Using a Good Proxy or an Localhost Proxy, i cannot replicate this bevahiour.
Its probably a low ip quality which gets you flagged by google, so you cant even access their login site.
Ive run a Quality Check on the IP shown in the Video:
![IP Quality](https://github.com/Vinyzu/Botright/assets/50874994/b62058f3-f379-4d97-9164-3b67f6108c1f)

So my best guess is that Google just flags your IP and just doesnt send you a response back for the site html request.
I dont see any issue in botrights, or playwrights code.
