### ISSUE TITLE
 installing issue

### ISSUE THREAD

**Issue by AL280** [Vinyzu/Botright#8]
Hello when i try installing i get this issue and i restarded pc but still

**Comment by AL280** [comment]
https://media.discordapp.net/attachments/1045472879313162312/1045856711677841459/error.png

**Comment by Vinyzu** [comment]
What Python Version are you running on?

**Comment by BlueSchnabeltier** [comment]
> https://media.discordapp.net/attachments/1045472879313162312/1045856711677841459/error.png

Try formating C:

**Comment by Vinyzu** [comment]
No further information given.
