### ISSUE TITLE
How to use the --incognito flag with Botright?

### ISSUE THREAD

**Issue by giauphan** [Vinyzu/Botright#82]
**Describe your quesiton**
I would like to know how to use the --incognito flag with Botright.

**Expected behavior**
I expect to be able to launch a browser instance with the --incognito flag enabled using Botright.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04
- Python version:  3.10
- Botright version: 0.5.1

**Additional context**
I've tried passing the --incognito flag as an argument when creating a new Browser instance, but it doesn't seem to work. Is there a specific way to enable incognito mode with Botright? Any guidance on this issue would be greatly appreciated. Thank you!

**Comment by Vinyzu** [comment]
You can append to botrights predefined flags by using
`botright_client.flags.append("--incognito")`

Note: The incognito flag is already used, so this wouldnt have any affect.
