### ISSUE TITLE
Error while installing botright (with pip) [BUG] 

### ISSUE THREAD

**Issue by fontrendererobj** [Vinyzu/Botright#94]
Command: "pip install botright"

Output:

Collecting botright
  Using cached botright-0.5.1-py3-none-any.whl.metadata (11 kB)
Collecting async-class (from botright)
  Using cached async-class-0.5.0.tar.gz (5.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httpx>=0.24.1 in c:\users\fontr\appdata\local\programs\python\python312\lib\site-packages (from botright) (0.27.0)
Collecting playwright>=1.40.0 (from botright)
  Using cached playwright-1.43.0-py3-none-win_amd64.whl.metadata (3.5 kB)
Collecting undetected-playwright-patch (from botright)
  Using cached undetected_playwright_patch-1.40.0.post1700587210000-py3-none-win_amd64.whl.metadata (5.5 kB)
Collecting pybrowsers>=0.5.2 (from botright)
  Using cached pybrowsers-0.5.2-py3-none-any.whl.metadata (7.9 kB)
Collecting chrome-fingerprints (from botright)
  Using cached chrome_fingerprints-1.1-py3-none-any.whl.metadata (3.2 kB)
Collecting numpy (from botright)
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting hcaptcha-challenger>=0.10.1.post1 (from botright)
  Using cached hcaptcha_challenger-0.10.1.post2-py3-none-any.whl.metadata (7.5 kB)
Collecting recognizer (from botright)
  Using cached recognizer-1.4-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: setuptools in c:\users\fontr\appdata\local\programs\python\python312\lib\site-packages (from botright) (69.5.1)
Requirement already satisfied: loguru in c:\users\fontr\appdata\local\programs\python\python312\lib\site-packages (from botright) (0.7.2)
Collecting ftfy (from hcaptcha-challenger>=0.10.1.post1->botright)
  Using cached ftfy-6.2.0-py3-none-any.whl.metadata (7.3 kB)
Collecting importlib_metadata (from hcaptcha-challenger>=0.10.1.post1->botright)
  Using cached importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
INFO: pip is looking at multiple versions of hcaptcha-challenger to determine which version is compatible with other requirements. This could take a while.
Collecting hcaptcha-challenger>=0.10.1.post1 (from botright)
  Using cached hcaptcha_challenger-0.10.1.post1-py3-none-any.whl.metadata (7.5 kB)
Collecting botright
  Using cached botright-0.5-py3-none-any.whl.metadata (11 kB)
  Using cached botright-0.4.post1-py3-none-any.whl.metadata (10 kB)
Collecting playwright==1.37.0 (from botright)
  Using cached playwright-1.37.0-py3-none-win_amd64.whl.metadata (3.5 kB)
Collecting playwright-stealth==1.0.6 (from botright)
  Using cached playwright_stealth-1.0.6-py3-none-any.whl.metadata (2.2 kB)
Collecting fake-useragent==1.3.0 (from botright)
  Using cached fake_useragent-1.3.0-py3-none-any.whl.metadata (13 kB)
Collecting numpy==1.26.0 (from botright)
  Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting scipy==1.11.2 (from botright)
  Using cached scipy-1.11.2-cp312-cp312-win_amd64.whl.metadata (59 kB)
Collecting Pillow==10.0.1 (from botright)
  Using cached Pillow-10.0.1-cp312-cp312-win_amd64.whl.metadata (9.6 kB)
Collecting yolov5==7.0.12 (from botright)
  Using cached yolov5-7.0.12-py37.py38.py39.py310-none-any.whl.metadata (10 kB)
Collecting sentence-transformers (from botright)
  Using cached sentence_transformers-2.7.0-py3-none-any.whl.metadata (11 kB)
Collecting easyocr==1.7.1 (from botright)
  Using cached easyocr-1.7.1-py3-none-any.whl.metadata (11 kB)
Collecting Faker==19.6.1 (from botright)
  Using cached Faker-19.6.1-py3-none-any.whl.metadata (15 kB)
Collecting scikit-image==0.21.0 (from botright)
  Using cached scikit_image-0.21.0.tar.gz (22.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + meson setup C:\Users\fontr\AppData\Local\Temp\pip-install-vg43ouos\scikit-image_06f87b8af80542af9af1a1bc88acd54a C:\Users\fontr\AppData\Local\Temp\pip-install-vg43ouos\scikit-image_06f87b8af80542af9af1a1bc88acd54a\.mesonpy-geb01ezq -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\fontr\AppData\Local\Temp\pip-install-vg43ouos\scikit-image_06f87b8af80542af9af1a1bc88acd54a\.mesonpy-geb01ezq\meson-python-native-file.ini
      The Meson build system
      Version: 1.4.0
      Source dir: C:\Users\fontr\AppData\Local\Temp\pip-install-vg43ouos\scikit-image_06f87b8af80542af9af1a1bc88acd54a
      Build dir: C:\Users\fontr\AppData\Local\Temp\pip-install-vg43ouos\scikit-image_06f87b8af80542af9af1a1bc88acd54a\.mesonpy-geb01ezq
      Build type: native build
      Project name: scikit-image
      Project version: 0.21.0
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `cl /?` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `cc --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `gcc --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `clang --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `clang-cl /?` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"
      Running `pgcc --version` gave "[WinError 2] Das System kann die angegebene Datei nicht finden"

      A full log can be found at C:\Users\fontr\AppData\Local\Temp\pip-install-vg43ouos\scikit-image_06f87b8af80542af9af1a1bc88acd54a\.mesonpy-geb01ezq\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Vinyzu** [comment]
As the error states, this is an error from the scikit installation. Theres no issue in botright. If this issue persues, have a look in scikits issues.

**Comment by mayploit** [comment]
Did you solve it?

**Comment by mayploit** [comment]
I found the solution for myself. I just downgraded Python version from 3.12 to 3.10
